schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: "Bearer c8f58ee68eaa3ec8462be69dca5b7e"
        X-Exclude-Invalid: true
documents: "./graphql/**/*.graphql"
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
    config:
      strictScalars: true
      scalars:
        BooleanType: boolean
        CustomData: Record<string, unknown>
        Date: string
        DateTime: string
        FloatType: number
        IntType: number
        ItemId: string
        JsonField: unknown
        MetaTagAttributes: Record<string, string>
        UploadId: string
      # Optional, gives meta fields a leading underscore
      namingConvention:
        keep
        # enumValues: './pascalCaseWithUnderscores'
