// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

var Link$1 = {};

var $$Intl = {};

function ArticleListItem(Props) {
  var title = Props.title;
  var description = Props.description;
  var date = Props.date;
  var slug = Props.slug;
  var locale = Props.locale;
  var formattedDate = new Intl.DateTimeFormat(locale, {
          dateStyle: "full"
        }).format(new Date(date));
  return React.createElement("div", {
              className: "mb-6"
            }, React.createElement("h3", {
                  className: "text-2xl font-bold mb-1 text-yellow-500"
                }, React.createElement(Link, {
                      href: "/articles/" + slug,
                      children: title
                    })), React.createElement("small", {
                  className: "text-xs"
                }, formattedDate), React.createElement("p", {
                  className: "text-md"
                }, description));
}

var make = ArticleListItem;

var $$default = ArticleListItem;

export {
  Link$1 as Link,
  $$Intl ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
