// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Io from "react-icons/io";

var GithubIcon = {};

var TwitterIcon = {};

function Bio(Props) {
  var content = Props.content;
  return React.createElement("div", {
              className: "flex flex-row"
            }, React.createElement("img", {
                  className: "rounded-full mr-4 w-16 h-16",
                  src: "http://placehold.it/100x100"
                }), React.createElement("div", {
                  className: "flex flex-col"
                }, React.createElement("div", undefined, React.createElement("div", {
                          className: "html font-serif bio",
                          dangerouslySetInnerHTML: {
                            __html: content
                          }
                        })), React.createElement("div", {
                      className: "flex flex-row gap-x-4 mt-2"
                    }, React.createElement("a", {
                          className: "text-yellow-500",
                          title: "Github link",
                          href: "https://github.com/DCKT",
                          target: "_blank"
                        }, React.createElement(Io.IoLogoGithub, {
                              size: 26
                            })), React.createElement("a", {
                          className: "text-yellow-500",
                          title: "Twitter link",
                          href: "https://twitter.com/DCK__",
                          target: "_blank"
                        }, React.createElement(Io.IoLogoTwitter, {
                              size: 26
                            })))));
}

var make = Bio;

var $$default = Bio;

export {
  GithubIcon ,
  TwitterIcon ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
